<?php

$lang = array(
	'__app_axenserverlist'	=>  '(aXen) Server List',
	'menutab__axenserverlist_icon' => 'server',
	'menutab__axenserverlist' => 'Server List',
	'menu__axenserverlist_servers' => 'Servers management',
	'menu__axenserverlist_servers_settings' => 'Settings',
	'menu__axenserverlist_servers_servers' => 'Servers',
	'axenserverlist_game' => 'Game',
	'axenserverlist_name' => 'Name',
	'axenserverlist_ip' => 'IP',
	'axenserverlist_owners' => 'Owners',
	'axenserverlist_statistics' => 'Statistics',
	'axenserverlist_tv' => 'TV',
	'axenserverlist_vote' => 'Vote',
	'axenserverlist_forum' => 'Forum',
	'axenserverlist_new' => 'New server?',
	'block_aXenServerListWidget' => 'Server List',
	'block_aXenServerListWidget_desc' => 'Widget shows servers',
	'aXenServerList_widget_title' => 'Our servers',
	'aXenServerList_settings_owners' => 'Show server owners?',
	'aXenServerList_settings_owners_desc' => 'If this option is disabled then serwer owners shows in more button',
	'aXenServerList_widget_more' => 'More',
	'aXenServerList_widget_connect' => 'Connect',
	'aXenServerList_widget_statistics' => 'Statistics',
	'aXenServerList_widget_vote' => 'Vote',
	'aXenServerList_widget_forum' => 'Forum',
	'aXenServerList_widget_tv' => 'TV'
);
