<ips:template parameters="$servers, $fullWidthPage" />
{{$totalServersDebug = 0;}}

{{foreach $servers as $row}}
{{if $row['debug']}}
{{$totalServersDebug += 1;}}
{{endif}}
{{endforeach}}

{{if $totalServersDebug}}
<a href="#" class="ipsType_noUnderline aXenServerList_toggle aXenServerList_toggle_debug ipsMargin_right{{if !$fullWidthPage}} md:ipsMargin_right:none{{endif}}" id="aXenServerList_toggle_debug" data-ipsmenu data-ipstooltip title="{lang='aXenServerList_widget_toggle_debug'}"><span class='ipsNotificationCount'>{$totalServersDebug}</span></a>

<div id="aXenServerList_toggle_debug_menu" class="ipsMenu ipsMenu_wide ipsHide">
  <div class="aXenServerList_debug ipsPadding:half">
    <ul class="aXenServerList_debug_list">
      {{foreach $servers as $row}}
      {{if $row['debug']}}
      <li>
        <span>
          {{$icon = $row["mod_icon"];}}
          {{if settings.lazy_load_enabled}}
          <img src='{expression="\IPS\Text\Parser::blankImage()"}' data-src='{{if $icon}}{file="$icon" extension="axenserverlist_mods"}{{else}}{resource="icons/unknown.png" app="axenserverlist" location="global"}{{endif}}' class="aXenServerList_debug:img" data-ipstooltip _title="{$row['mod_name']}" alt="{$row['mod_name']}">
          {{else}}
            <img src='{{if $icon}}{file="$icon" extension="axenserverlist_mods"}{{else}}{resource="icons/unknown.png" app="axenserverlist" location="global"}{{endif}}' class="aXenServerList_debug:img" data-ipstooltip _title="{$row['mod_name']}" alt="{$row['mod_name']}">
            {{endif}}

            <span class="aXenServerList_debug:name">{$row['name_default'] ? $row['name_default_text'] : $row['name']}</span>
        </span>

        <span>
          {{$topServerLang = $row['debug_text_YesNo'] ? 'axenserverlist_debug_text_' . $row['id'] : 'aXenServerList_debug_icon';}}
          {lang="$topServerLang"}
        </span>

      </li>
      {{endif}}
      {{endforeach}}
    </ul>
  </div>
</div>
{{endif}}
