<ips:template parameters="$row" />
<div id="aXenServerList_{$row['axenserverlist_id']}_menu" class="ipsMenu aXenServerListMenu{{if settings.aXenServerList_settings_fullWidth && ( (isset(\IPS\Request::i()->cookie['aXenServerList_widget_fullWidth']) && settings.aXenServerList_settings_fullWidth_control && isset(\IPS\Request::i()->cookie['aXenServerList_widget_fullWidth_manual'])) || !settings.aXenServerList_settings_fullWidth_control || (!isset(\IPS\Request::i()->cookie['aXenServerList_widget_fullWidth_manual']) && settings.aXenServerList_settings_fullWidth_default) )}} aXenServerListMenu_fullWidth{{endif}} ipsHide">
  <div class="aXenServerList_item_more_menu ipsPadding:half">

    {{if $row['axenserverlist_debug'] && $row['axenserverlist_debug_text_YesNo'] }}
    <div class="ipsMessage ipsMessage_warning">
      {{$topServerLang = 'axenserverlist_debug_text_' . $row['axenserverlist_id'];}}
      {lang="$topServerLang"}
    </div>
    {{endif}}

    <ul class="aXenServerList_item_more_info{{if !$row['axenserverlist_forum'] || !$row['axenserverlist_vote'] || !$row['axenserverlist_statistics'] || !$row['axenserverlist_tv']}} aXenServerList_item_more_info:fullWidth{{endif}}">
      {{if $row['axenserverlist_owners']}}
      <li class="aXenServerList_item_more_info:owners">
        <span><i class="fa fa-users"></i> {lang='aXenServerList_widget_owners'}</span>
        <span>
          <ul class="ipsList_reset">
            {{foreach array_filter(explode(',', $row['axenserverlist_owners'])) as $owner}}
            <li>
              {{$member = \IPS\Member::load( $owner );}}
              {$member->link()|raw}
            </li>
            {{endforeach}}
          </ul>
        </span>
      </li>
      {{endif}}

      <li>
        <span><i class="fa fa-map"></i> {lang='aXenServerList_widget_map'}</span>
        <span>
          {{if $row['axenserverlist_map']}}{$row['axenserverlist_map']}
          {{else}}{lang='aXenServerList_widget_none'}{{endif}}
        </span>
      </li>

      <li>
        <span><i class="fa fa-server"></i> {lang='aXenServerList_widget_protocol'}</span>
        <span>
          {{if $row['axenserverlist_protocol']}}{$row['axenserverlist_protocol']}
          {{else}}{lang='aXenServerList_widget_none'}{{endif}}
        </span>
      </li>

      <li>
        <span><i class="fa {{if $row['axenserverlist_password']}}fa-lock{{else}}fa-unlock{{endif}}"></i> {lang='aXenServerList_widget_password'}</span>
        <span>
          {{if $row['axenserverlist_password']}}{lang='yes'}
          {{else}}{lang='no'}{{endif}}
        </span>
      </li>

      <li>
        <span><i class="fa fa-percent"></i> {lang='aXenServerList_widget_percent_players'}</span>
        <span>
          {$row['axenserverlist_max_players'] ? round( ($row['axenserverlist_current_players'] * 100) / $row['axenserverlist_max_players'] ) : 0}%
        </span>
      </li>

      <li>
        <span><i class="fa fa-users"></i> {lang='aXenServerList_widget_most_players'}</span>
        <span>
          {$row['axenserverlist_most_players']}
        </span>
      </li>
    </ul>

    {{if $row['axenserverlist_forum'] || $row['axenserverlist_vote'] || $row['axenserverlist_statistics'] || $row['axenserverlist_tv']}}
    <ul class="aXenServerList_item_more_menu_links">
      {{if $row['axenserverlist_vote']}}
      <li>
        <a href="{$row['axenserverlist_vote']}" class="ipsButton ipsButton_fullWidth {setting='aXenServerList_settings_buttons_vote'}" target="_blank" rel="noopener nofollow">
          <i class="fa fa-plus"></i> {lang='aXenServerList_widget_vote'}
        </a>
      </li>
      {{endif}}

      {{if $row['axenserverlist_statistics']}}
      <li>
        <a href="{$row['axenserverlist_statistics']}" class="ipsButton ipsButton_fullWidth {setting='aXenServerList_settings_buttons_statistics'}" target="_blank" rel="noopener nofollow">
          <i class="fa fa-bar-chart"></i> {lang='aXenServerList_widget_statistics'}
        </a>
      </li>
      {{endif}}

      {{if $row['axenserverlist_tv']}}
      <li>
        <a href="{$row['axenserverlist_tv']}" class="ipsButton ipsButton_fullWidth {setting='aXenServerList_settings_buttons_tv'}" target="_blank" rel="noopener nofollow">
          <i class="fa fa-video-camera"></i> {lang='aXenServerList_widget_tv'}
        </a>
      </li>
      {{endif}}

      {{if $row['axenserverlist_forum']}}
      <li>
        <a href="{$row['axenserverlist_forum']}" class="ipsButton ipsButton_fullWidth {setting='aXenServerList_settings_buttons_forum'}">
          <i class="fa fa-comments"></i> {lang='aXenServerList_widget_forum'}
        </a>
      </li>
      {{endif}}
    </ul>
    {{endif}}
  </div>
</div>