<ips:template parameters="$row" />
<li class="ipsDataItem">
  <ul class="ipsList_reset aXenServerList_item">
    <li class="aXenServerList_item_title">
      <span class="aXenServerList_item_title:status{{if $row['axenserverlist_status']}} aXenServerList_item_title:status-online{{endif}}"></span>

      <img src="{setting=" base_url"}applications/axenserverlist/interface/icons/{$row['axenserverlist_game']}.png" class="aXenServerList_item_title:img" data-ipstooltip _title="{$row['axenserverlist_game_long']}" alt="{$row['axenserverlist_game_long']}">

      <span class="aXenServerList_item_title:name">
        {{if $row['axenserverlist_top_server']}}
        {{$topServerLang = 'axenserverlist_top_server_text_' . $row['axenserverlist_id'];}}
        <i class="fa fa-trophy" {{if $row['axenserverlist_top_server'] && $row['axenserverlist_top_server_text']}}data-ipstooltip title="{lang='{$topServerLang}'}" {{endif}}></i>
        {{endif}}

        {{if $row['axenserverlist_new']}}
        <span class="ipsBadge ipsBadge_negative">{lang="aXenServerList_widget_new"}</span>
        {{endif}}

        {{$getName = $row['axenserverlist_name_default'] ? $row['axenserverlist_name_default_text'] : $row['axenserverlist_name'];}}
        {$getName}
      </span>
    </li>

    <li class="aXenServerList_item:ip">
      {{if $row['axenserverlist_connect_link']}}
      <a href="{$row['axenserverlist_connect_link']}" class="ipsButton ipsButton_verySmall ipsButton_light ipsResponsive_showDesktop" data-ipstooltip title="{lang='aXenServerList_widget_connect'}">
        <i class="fa fa-link"></i>
      </a>
      {{endif}}

      {{$getIP = $row['axenserverlist_ip_custom'] ? $row['axenserverlist_ip_custom'] : $row['axenserverlist_ip'];}}

      {$getIP}
    </li>


    <li class="aXenServerList_item_players">
      {{$calcPlayers = $row['axenserverlist_max_players'] ? round( ($row['axenserverlist_current_players'] * 100) / $row['axenserverlist_max_players'] ) : 0;}}

      <svg xmlns="http://www.w3.org/2000/svg" class="aXenServerList_item_players_svg" viewBox="0 0 49 40.22">
        <path class="aXenServerList_item_players_svg:none" d="M1048.02,1119.34a22.5,22.5,0,1,1,37.15-.28" transform="translate(-1042 -1082)"></path>
        <path class="aXenServerList_item_players_svg:fill" d="M1048.02,1119.34a22.5,22.5,0,1,1,37.15-.28" transform="translate(-1042 -1082)" style="stroke-dashoffset: calc(98px - {$calcPlayers}px);"></path>
      </svg>

      <span>{$row['axenserverlist_current_players']} / {$row['axenserverlist_max_players']}</span>
    </li>

    {{if settings.aXenServerList_settings_owners && $row['axenserverlist_owners']}}
    <li class="aXenServerList_item_owners">
      <ul class="aXenServerList_item_owners_ul">
        {{foreach array_filter(explode(',', $row['axenserverlist_owners'])) as $owner}}
        <li>
          {{$member = \IPS\Member::load( $owner );}}
          {$member->link()|raw}
        </li>
        {{endforeach}}
      </ul>
    </li>
    {{endif}}

    <li class="aXenServerList_item_more">
      <button class="ipsButton ipsButton_fullWidth ipsButton_important" id="aXenServerList_{$row['axenserverlist_id']}" data-ipsmenu>
        <i class="fa fa-info"></i> {lang="aXenServerList_widget_more"}
      </button>

      {template="more" app="axenserverlist" group="servers" location="front" params="$row"}
    </li>
  </ul>
</li>