<ips:template parameters="$row" />
{{$icon = $row["mod_icon"];}}

<li class="ipsDataItem">
  <ul class="ipsList_reset aXenServerList_item">
    <li class="aXenServerList_item_title">
      <span class="aXenServerList_item_title:status{{if $row['status']}} aXenServerList_item_title:status-online{{endif}}"></span>

      {{if settings.lazy_load_enabled}}
      <img src='{expression="\IPS\Text\Parser::blankImage()"}' data-src='{{if $icon}}{file="$icon" extension="axenserverlist_mods"}{{else}}{resource="icons/unknown.png" app="axenserverlist" location="global"}{{endif}}' class="aXenServerList_item_title:img" data-ipstooltip _title="{$row['mod_name']}" alt="{$row['mod_name']}">
      {{else}}
        <img src='{{if $icon}}{file="$icon" extension="axenserverlist_mods"}{{else}}{resource="icons/unknown.png" app="axenserverlist" location="global"}{{endif}}' class="aXenServerList_item_title:img" data-ipstooltip _title="{$row['mod_name']}" alt="{$row['mod_name']}">
        {{endif}}

        <span class="aXenServerList_item_title:name">
          {{if $row['debug']}}
          <i class="fa fa-exclamation-triangle" data-ipstooltip title="{lang='aXenServerList_debug_icon'}"></i>
          {{endif}}

          {{if $row['top_server']}}
          {{$topServerLang = 'axenserverlist_top_server_text_' . $row['id'];}}
          <i class="fa fa-trophy" {{if $row['top_server'] && isset($row['top_server_text'])}}data-ipstooltip title="{lang='{$topServerLang}'}" {{endif}}></i>
          {{endif}}

          {{if $row['new']}}
            <span class="ipsBadge ipsBadge_negative">{lang="aXenServerList_widget_new"}</span>
          {{endif}}

          {$row['name_default'] ? $row['name_default_text'] : $row['name']}
        </span>
    </li>

    <li class="aXenServerList_item:ip">
      {{if $row['custom_connect']}}
      <a href="{$row['custom_connect_link']}" class="ipsButton aXenServerListButton ipsButton_light{{if $row['mod_protocol'] != 'discord'}} ipsResponsive_showDesktop{{endif}}" data-ipstooltip title="{lang='aXenServerList_widget_connect'}" {{if $row['mod_protocol'] == 'discord'}}target="blank" {{endif}}>
        <i class="fa fa-link"></i>
      </a>
      {{elseif $row['url_connect']}}
      <a href="{$row['url_connect']}" class="ipsButton aXenServerListButton ipsButton_light{{if $row['mod_protocol'] != 'discord'}} ipsResponsive_showDesktop{{endif}}" data-ipstooltip title="{lang='aXenServerList_widget_connect'}" {{if $row['mod_protocol'] == 'discord'}}target="blank" {{endif}}>
        <i class="fa fa-link"></i>
      </a>
      {{endif}}

      {{if $row['mod_protocol'] == 'discord' && !$row['ip_custom']}}
      {lang="aXenServerList_widget_clickToConnect"}
      {{else}}{$row['ip_custom'] ? $row['ip_custom'] : $row['ip']}{{endif}}
    </li>


    <li class="aXenServerList_item_players">
      {{$calcPlayers = $row['max_players'] ? round( ($row['current_players'] * 100) / $row['max_players'] ) : 0;}}
      {{$calcPlayers = $calcPlayers <= 100 ? $calcPlayers : 100;}}

      <svg xmlns="http://www.w3.org/2000/svg" class="aXenServerList_item_players_svg" viewBox="0 0 49 40.22">
        <path class="aXenServerList_item_players_svg:none" d="M1048.02,1119.34a22.5,22.5,0,1,1,37.15-.28" transform="translate(-1042 -1082)"></path>
        <path class="aXenServerList_item_players_svg:fill{{if $calcPlayers > 0 && $calcPlayers <= 20}} aXenServerList_item_players_svg:fill_1_20{{elseif $calcPlayers > 20 && $calcPlayers <= 40 }} aXenServerList_item_players_svg:fill_21_40{{elseif $calcPlayers > 40 && $calcPlayers <= 60 }} aXenServerList_item_players_svg:fill_41_60{{elseif $calcPlayers > 60 && $calcPlayers <= 80 }} aXenServerList_item_players_svg:fill_61_80{{elseif $calcPlayers > 80 }} aXenServerList_item_players_svg:fill_81_100{{endif}}" d="M1048.02,1119.34a22.5,22.5,0,1,1,37.15-.28" transform="translate(-1042 -1082)" style="stroke-dashoffset: calc(100px - {$calcPlayers}px);"></path>
      </svg>

      <span>{$row['current_players']} / {$row['max_players']}</span>
    </li>

    {{if $row['owners']}}
    <li class="aXenServerList_item_owners">
      <ul class="aXenServerList_item_owners_ul">
        {{foreach array_filter(explode(',', $row['owners'])) as $owner}}
        <li>
          {{$member = \IPS\Member::load( $owner );}}
          {$member->link()|raw}
        </li>
        {{endforeach}}
      </ul>
    </li>
    {{endif}}

    <li class="aXenServerList_item_more">
      <ul class="aXenServerList_item_more_ul">
        {{if $row['url_vote']}}
        <li>
          <a href="{$row['url_vote']}" class="ipsButton aXenServerListButton {setting='aXenServerList_settings_buttons_vote'}" target="_blank" rel="noopener nofollow" data-ipstooltip title="{lang='aXenServerList_widget_vote'}">
            <i class="fa fa-plus"></i>
          </a>
        </li>
        {{endif}}

        {{if $row['url_statistics']}}
        <li>
          <a href="{$row['url_statistics']}" class="ipsButton aXenServerListButton {setting='aXenServerList_settings_buttons_statistics'}" target="_blank" rel="noopener nofollow" data-ipstooltip title="{lang='aXenServerList_widget_statistics'}">
            <i class="fa fa-bar-chart"></i>
          </a>
        </li>
        {{endif}}

        {{if $row['url_tv']}}
        <li>
          <a href="{$row['url_tv']}" class="ipsButton aXenServerListButton {setting='aXenServerList_settings_buttons_tv'}" target="_blank" rel="noopener nofollow" data-ipstooltip title="{lang='aXenServerList_widget_tv'}">
            <i class="fa fa-video-camera"></i>
          </a>
        </li>
        {{endif}}

        {{if $row['url_forum']}}
        <li>
          <a href="{$row['url_forum']}" class="ipsButton aXenServerListButton {setting='aXenServerList_settings_buttons_forum'}" data-ipstooltip title="{lang='aXenServerList_widget_forum'}">
            <i class="fa fa-comments"></i>
          </a>
        </li>
        {{endif}}

        <li>
          <button class="ipsButton aXenServerListButton ipsButton_normal" id="aXenServerList_{$row['id']}" data-ipsmenu data-ipstooltip title="{lang='aXenServerList_widget_more'}">
            <i class="fa fa-info-circle"></i>
          </button>

          {template="more" app="axenserverlist" group="servers" location="front" params="$row"}
        </li>
      </ul>
    </li>
  </ul>
</li>
