<ips:template parameters="$servers" />
<h3 class="ipsType_reset ipsWidget_title ipsFlex ipsFlex-jc:between aXenServerList {{if isset( \IPS\Request::i()->cookie['aXenServerList_widget_toggle'] )}} aXenServerList_hide{{endif}}">
  <span>{lang="aXenServerList_widget_title"}</span>

  <a href="#" class="ipsType_noUnderline aXenServerList_toggle" data-ipstooltip title="{lang='aXenServerList_widget_toggle'}"></a>
</h3>

{{if settings.aXenServerList_settings_footer}}
{{$totalServers = 0;}}
{{$totalPlayers = 0;}}
{{$totalPlayersMax = 0;}}
{{endif}}

<ul class="aXenServerList_ul">
  {{foreach $servers as $row}}

  {{if settings.aXenServerList_settings_footer}}
  {{$totalServers += 1;}}
  {{$totalPlayers += $row['axenserverlist_current_players'];}}
  {{$totalPlayersMax += $row['axenserverlist_max_players'];}}
  {{endif}}

  {template="row" app="axenserverlist" group="servers" location="front" params="$row"}
  {{endforeach}}
</ul>

{template="footer" app="axenserverlist" group="servers" location="front" if="settings.aXenServerList_settings_footer" params="$totalServers, $totalPlayers, $totalPlayersMax"}