<ips:template parameters="$servers" />
<h3 class="ipsType_reset ipsWidget_title">{lang="aXenServerList_widget_title"}</h3>

<ul class="aXenServerList">
  {{foreach $servers as $row}}
  <li>
    <ul class="ipsList_reset aXenServerList_item">
      <li class="aXenServerList_item:status{{if $row['axenserverlist_status']}} aXenServerList_item:status-online{{endif}}">
        <span></span>
      </li>

      <li class="aXenServerList_item:img">
        <img src="{setting=" base_url"}applications/axenserverlist/interface/icons/{$row['axenserverlist_game']}.png" data-ipstooltip _title="{$row['axenserverlist_game_long']}" alt="{$row['axenserverlist_game_long']}">
      </li>

      <li class="aXenServerList_item:name">
        {$row['axenserverlist_name']}
      </li>

      <li class="aXenServerList_item:ip">
        {$row['axenserverlist_ip']}
      </li>

      <li class="aXenServerList_item_players">
        {{$calcPlayers = $row['axenserverlist_max_players'] ? round( ($row['axenserverlist_current_players'] * 100) / $row['axenserverlist_max_players'] ) : 0;}}

        <svg xmlns="http://www.w3.org/2000/svg" class="aXenServerList_item_players_svg" viewBox="0 0 49 40.22">
          <path class="aXenServerList_item_players_svg:none" d="M1048.02,1119.34a22.5,22.5,0,1,1,37.15-.28" transform="translate(-1042 -1082)"></path>
          <path class="aXenServerList_item_players_svg:fill" d="M1048.02,1119.34a22.5,22.5,0,1,1,37.15-.28" transform="translate(-1042 -1082)" style="stroke-dashoffset: calc(98px - {$calcPlayers}px);"></path>
        </svg>

        <span>{$row['axenserverlist_current_players']} / {$row['axenserverlist_max_players']}</span>
      </li>

      {{if settings.aXenServerList_settings_owners}}
      <li class="aXenServerList_item:owners">
        {{foreach array_filter(explode(',', $row['axenserverlist_owners'])) as $owner}}
        {{$member = \IPS\Member::load( $owner );}}
        <span>{$member->link()|raw}</span>
        {{endforeach}}
      </li>
      {{endif}}

      <li class="aXenServerList_item_more">
        <a class="ipsButton ipsButton_verySmall ipsButton_important"><i class="fa fa-info" aria-hidden="true"></i></a>
      </li>
    </ul>
  </li>
  {{endforeach}}
</ul>